# Generated by Django 3.0.4 on 2022-06-16 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('System', models.CharField(max_length=25)),
                ('Hostname', models.CharField(max_length=50)),
                ('Host_IP', models.CharField(max_length=50)),
                ('Processor', models.CharField(max_length=100)),
                ('Machine', models.CharField(max_length=25)),
                ('Version', models.CharField(max_length=100)),
            ],
        ),
    ]
