# Generated by Django 3.0.4 on 2022-06-18 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BostonV1_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_data',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CPU_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Physical_cores', models.IntegerField()),
                ('Total_cores', models.IntegerField()),
                ('Total_CPU_Usage', models.IntegerField()),
                ('Turbo_Min', models.IntegerField()),
                ('Turbo_Max', models.IntegerField()),
                ('Turbo_Current', models.IntegerField()),
                ('cpu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BostonV1_app.Server_Data')),
            ],
        ),
    ]
