# Generated by Django 3.0.4 on 2022-06-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BostonV1_app', '0004_auto_20220618_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu_data',
            name='server_data',
        ),
    ]
