# Generated by Django 3.0.4 on 2022-06-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BostonV1_app', '0005_remove_cpu_data_server_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_data',
            name='server_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BostonV1_app.Server_Data', verbose_name='server'),
        ),
    ]
