# Generated by Django 3.0.4 on 2022-06-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BostonV1_app', '0008_auto_20220618_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_RAM', models.CharField(max_length=20)),
                ('Available_RAM', models.CharField(max_length=20)),
                ('Used_RAM', models.CharField(max_length=20)),
                ('Used_Percentage', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cpu_data',
            name='server_data',
        ),
    ]
