# Generated by Django 3.0.4 on 2022-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BostonV1_app', '0009_auto_20220618_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Partitions', models.IntegerField()),
                ('Total_Available', models.CharField(max_length=20)),
                ('Total_Usage', models.CharField(max_length=20)),
                ('Total_Free', models.CharField(max_length=20)),
            ],
        ),
    ]
